### PR TITLE
Update examples to use base collection

### PR DESCRIPTION
**Pull request by blob1807**
Changed examples to use the base collection for all relevant imports.

### CODE REVIEW

**Comment by floooh** [comment]
Excuse my ignorance, but what's the difference and why is base: better?

**Comment by floooh** [comment]
Hmm ok, has runtime been moved from core: into base: recently?

I don't find it here: https://pkg.odin-lang.org/core/

...but here: https://pkg.odin-lang.org/base/

**Comment by floooh** [comment]
Merged, thanks!

**Comment by blob1807** [comment]
Yes runtime. intrinsics & builtin were moved from core to base as they're a required part of Odin that all compliers should have. Where as core isn't.

**Pull request merged**
