### PR TITLE
Add Odin helpers

### PR DESCRIPTION
**Pull request by jakubtomsu**
This PR adds a few utilities to help with integrating sokol into odin projects.
- `logger.odin`: Hooks sokol logger into the native odin logging system
- `allocator.odin`: Hooks the sokol allocators into the native odin allocator system
- `glue.odin`: re-implementation of sokol_glue.h in Odin. I'm not sure if it's a good idea to have this in the official repo. But I use this in my own projects to minimize C dependencies (for simplicity), since it's less than 20 lines of code...

> Note: Currently the logger and allocator pass pointer to [Odin Context](https://odin-lang.org/docs/overview/#implicit-context-system) as `user_data`. This works well for all my use cases

Also, I forgot to add `/Z7` argument to generate proper debug info in my last PRs, so here it is :)

Example usage:
```odin
    sapp.run(
         {
            init_cb = _app_init,
            frame_cb = _app_frame,
            cleanup_cb = _app_cleanup,
            event_cb = _app_event,
            fullscreen = true,
            logger = transmute(sapp.Logger)shelp.logger(&g_state.base_context),
            allocator = transmute(sapp.Allocator)shelp.allocator(&g_state.base_context),
        },
    )
```
```odin
    sg.setup(
         {
            environment = shelp.glue_environment(),
            logger = transmute(sg.Logger)shelp.logger(&g_state.base_context),
            allocator = transmute(sg.Allocator)shelp.allocator(&g_state.base_context),
        },
    )
```
```odin
        sg.begin_pass({label = "swapchain", swapchain = shelp.glue_swapchain()})
        defer sg.end_pass()
```

### CODE REVIEW

**Comment by floooh** [comment]
Apologies for being mostly quiet this week. Will resume work on the weekend :)

**Comment by jakubtomsu** [comment]
No worries :)

**Comment by floooh** [comment]
Hmm, the glue helper is indeed a bit weird but since it's optional I guess it's ok.

Only downside is that I will most likely forget to update it when I add new members to `sg_environment` and/or `sg_swapchain` (e.g. the next sokol-gfx update will get a new `gl` item in `sg_environment`:

https://github.com/floooh/sokol/blob/ca23e460e61073dd5fcd69b4af9e670355323c53/sokol_gfx.h#L3805-L3816

I'll merge the PR, but this is something we need to keep in mind for such manually added helper functions.

**Comment by jakubtomsu** [comment]
Right, I know keeping 2 implementations in sync is not fun... I'll try to update it every time I upgrade to latest sokol version.

**Pull request merged**
