### PR TITLE
Added dynamic library support for macos.

### PR DESCRIPTION
**Pull request by barnamumtyan**
Fixed [dynamic library support on macos issue](https://github.com/floooh/sokol-odin/issues/14)

### CODE REVIEW

**Comment by floooh** [comment]
Thanks for the PR, one important change is needed though:

The changes to the *.odin files would be overwritten on the next commit to the sokol repository, because those files are code-generated. Instead please provide a separate PR into the sokol repositories which changes the `bindgen/gen_odin.py` file in this block:

https://github.com/floooh/sokol/blob/4483275d3b0be2c5ac23d8054bc66d3cb4ff75ec/bindgen/gen_odin.py#L374-L391

...also see @jakubtomsu's PR which (among other things) added the DLL support for Windows: https://github.com/floooh/sokol/pull/1023

...and the PR into sokol-odin should only contain the `.gitignore` and `build_clibs_macos_dylib.sh` file.

**Comment by barnamumtyan** [comment]
Understood, I'll fix it.

**Comment by floooh** [comment]
Thanks! Can you still have a look at the diffs in the .odin files in this PR? It looks like there's whitespace changes in the else-branches. Without those the PR would only affect two files, as intended.

**Comment by floooh** [comment]
Looking good now, thanks! I'll try to merge the two PRs on Monday after a bit of testing (tomorrow I'll be travelling).

**Comment by floooh** [comment]
Ok, merged this first, then next when I merge the sokol PR, the code generation CI should kick in and update sokol-odin.

**Comment by floooh** [comment]
...and done: https://github.com/floooh/sokol-odin/commit/4dea3f69bf90bd1d51595e420e99c994b2a6f825

**Pull request merged**
